//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPPhotoEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPPhotoEditor.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Angle 的本地化字符串。
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the picture 的本地化字符串。
        /// </summary>
        public static string APChangeThePicture {
            get {
                return ResourceManager.GetString("APChangeThePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop 的本地化字符串。
        /// </summary>
        public static string APCrop {
            get {
                return ResourceManager.GetString("APCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crop Proportion 的本地化字符串。
        /// </summary>
        public static string APCropProportion {
            get {
                return ResourceManager.GetString("APCropProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Horizontal 的本地化字符串。
        /// </summary>
        public static string APFlipHorizontal {
            get {
                return ResourceManager.GetString("APFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Vertical 的本地化字符串。
        /// </summary>
        public static string APFlipVertical {
            get {
                return ResourceManager.GetString("APFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string APHeight {
            get {
                return ResourceManager.GetString("APHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep the proportion 的本地化字符串。
        /// </summary>
        public static string APKeepTheProportion {
            get {
                return ResourceManager.GetString("APKeepTheProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Size 的本地化字符串。
        /// </summary>
        public static string APNewSize {
            get {
                return ResourceManager.GetString("APNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string APOK {
            get {
                return ResourceManager.GetString("APOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proportion 的本地化字符串。
        /// </summary>
        public static string APProportion {
            get {
                return ResourceManager.GetString("APProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume 的本地化字符串。
        /// </summary>
        public static string APResume {
            get {
                return ResourceManager.GetString("APResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 的本地化字符串。
        /// </summary>
        public static string APRotate {
            get {
                return ResourceManager.GetString("APRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string APSize {
            get {
                return ResourceManager.GetString("APSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string APWidth {
            get {
                return ResourceManager.GetString("APWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have change to brush model! 的本地化字符串。
        /// </summary>
        public static string ChangeToBrush {
            get {
                return ResourceManager.GetString("ChangeToBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have change to eraser model! 的本地化字符串。
        /// </summary>
        public static string ChangeToEraser {
            get {
                return ResourceManager.GetString("ChangeToEraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image in current layer will be cleared. 的本地化字符串。
        /// </summary>
        public static string CLClearImageConfirm {
            get {
                return ResourceManager.GetString("CLClearImageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity mask of current layer will be cleared. 的本地化字符串。
        /// </summary>
        public static string CLClearOpacityMaskConfirm {
            get {
                return ResourceManager.GetString("CLClearOpacityMaskConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string CPAdd {
            get {
                return ResourceManager.GetString("CPAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double tap the image to show the toolbar. 的本地化字符串。
        /// </summary>
        public static string CPDoubleTapToShowToolBar {
            get {
                return ResourceManager.GetString("CPDoubleTapToShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag 的本地化字符串。
        /// </summary>
        public static string CPDrag {
            get {
                return ResourceManager.GetString("CPDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pen 的本地化字符串。
        /// </summary>
        public static string CPPen {
            get {
                return ResourceManager.GetString("CPPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string CPRedo {
            get {
                return ResourceManager.GetString("CPRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string CPSave {
            get {
                return ResourceManager.GetString("CPSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string CPSetting {
            get {
                return ResourceManager.GetString("CPSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        public static string CPStyle {
            get {
                return ResourceManager.GetString("CPStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string CPUndo {
            get {
                return ResourceManager.GetString("CPUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brush 的本地化字符串。
        /// </summary>
        public static string EBrush {
            get {
                return ResourceManager.GetString("EBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string EClear {
            get {
                return ResourceManager.GetString("EClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try to &apos;Hold&apos; and &apos;Double Tap&apos; 的本地化字符串。
        /// </summary>
        public static string ELayerGuideTip {
            get {
                return ResourceManager.GetString("ELayerGuideTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge the all layers? 的本地化字符串。
        /// </summary>
        public static string EMergeLayersConfirm {
            get {
                return ResourceManager.GetString("EMergeLayersConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ESave {
            get {
                return ResourceManager.GetString("ESave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent 的本地化字符串。
        /// </summary>
        public static string ETransparent {
            get {
                return ResourceManager.GetString("ETransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardness 的本地化字符串。
        /// </summary>
        public static string Feather {
            get {
                return ResourceManager.GetString("Feather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string GlCancel {
            get {
                return ResourceManager.GetString("GlCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t ask me again. 的本地化字符串。
        /// </summary>
        public static string GlDontAskMeAgain {
            get {
                return ResourceManager.GetString("GlDontAskMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want? 的本地化字符串。
        /// </summary>
        public static string GlDoYouWant {
            get {
                return ResourceManager.GetString("GlDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image saved to saved pictures album 的本地化字符串。
        /// </summary>
        public static string GlImageHaveSavedTo {
            get {
                return ResourceManager.GetString("GlImageHaveSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave 的本地化字符串。
        /// </summary>
        public static string GlLeave {
            get {
                return ResourceManager.GetString("GlLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave Collage ? 的本地化字符串。
        /// </summary>
        public static string GlLeaveCollage {
            get {
                return ResourceManager.GetString("GlLeaveCollage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave Paint ? 的本地化字符串。
        /// </summary>
        public static string GlLeavePaint {
            get {
                return ResourceManager.GetString("GlLeavePaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press the back key again ! =^_^= 的本地化字符串。
        /// </summary>
        public static string GlPressTheBackKeyAgain {
            get {
                return ResourceManager.GetString("GlPressTheBackKeyAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Give me 5 stars!More people use,more wonderful functions.Thank you! 的本地化字符串。
        /// </summary>
        public static string GlRateViewString {
            get {
                return ResourceManager.GetString("GlRateViewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image saved to saved pictures album! 的本地化字符串。
        /// </summary>
        public static string HadSaveTo {
            get {
                return ResourceManager.GetString("HadSaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have no Layer to save! 的本地化字符串。
        /// </summary>
        public static string HaveNoLayer {
            get {
                return ResourceManager.GetString("HaveNoLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Affect 的本地化字符串。
        /// </summary>
        public static string MAffect {
            get {
                return ResourceManager.GetString("MAffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        public static string MChange {
            get {
                return ResourceManager.GetString("MChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classical 的本地化字符串。
        /// </summary>
        public static string MClassical {
            get {
                return ResourceManager.GetString("MClassical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collage 的本地化字符串。
        /// </summary>
        public static string MCollage {
            get {
                return ResourceManager.GetString("MCollage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encourage us 的本地化字符串。
        /// </summary>
        public static string MEncourageUs {
            get {
                return ResourceManager.GetString("MEncourageUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string MFilter {
            get {
                return ResourceManager.GetString("MFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Begin 的本地化字符串。
        /// </summary>
        public static string MFreeBegin {
            get {
                return ResourceManager.GetString("MFreeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 give me a praise 的本地化字符串。
        /// </summary>
        public static string MGiveMeAPraise {
            get {
                return ResourceManager.GetString("MGiveMeAPraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install now? 的本地化字符串。
        /// </summary>
        public static string MInstallNow {
            get {
                return ResourceManager.GetString("MInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It will take effect at the next start! 的本地化字符串。
        /// </summary>
        public static string MItWillTakeEffectAtTheNextStart {
            get {
                return ResourceManager.GetString("MItWillTakeEffectAtTheNextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collage 的本地化字符串。
        /// </summary>
        public static string MMaskCollage {
            get {
                return ResourceManager.GetString("MMaskCollage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        public static string MMore {
            get {
                return ResourceManager.GetString("MMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movie Frame 的本地化字符串。
        /// </summary>
        public static string MMovieFrame {
            get {
                return ResourceManager.GetString("MMovieFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paint 的本地化字符串。
        /// </summary>
        public static string MPaint {
            get {
                return ResourceManager.GetString("MPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can hold and pin to the start! 的本地化字符串。
        /// </summary>
        public static string MPinTips {
            get {
                return ResourceManager.GetString("MPinTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 settings and about 的本地化字符串。
        /// </summary>
        public static string MSettingAndAbout {
            get {
                return ResourceManager.GetString("MSettingAndAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the background 的本地化字符串。
        /// </summary>
        public static string MTheBackground {
            get {
                return ResourceManager.GetString("MTheBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use default background 的本地化字符串。
        /// </summary>
        public static string MUseDefaultBackground {
            get {
                return ResourceManager.GetString("MUseDefaultBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Words Size 的本地化字符串。
        /// </summary>
        public static string MVWordsSize {
            get {
                return ResourceManager.GetString("MVWordsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have not installed &quot;Sketch Board&quot;. 的本地化字符串。
        /// </summary>
        public static string MYouHaveNotInstalledSketchBoard {
            get {
                return ResourceManager.GetString("MYouHaveNotInstalledSketchBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It  only supports 5 layers! 的本地化字符串。
        /// </summary>
        public static string OnlyLayer {
            get {
                return ResourceManager.GetString("OnlyLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string OPAbout {
            get {
                return ResourceManager.GetString("OPAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy the full version 的本地化字符串。
        /// </summary>
        public static string OPBuyTheFullVersion {
            get {
                return ResourceManager.GetString("OPBuyTheFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No ads,more service. 的本地化字符串。
        /// </summary>
        public static string OPBuyTheFullVersionDetail {
            get {
                return ResourceManager.GetString("OPBuyTheFullVersionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string OPGeneral {
            get {
                return ResourceManager.GetString("OPGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More apps 的本地化字符串。
        /// </summary>
        public static string OPMoreApps {
            get {
                return ResourceManager.GetString("OPMoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 more excellent apps 的本地化字符串。
        /// </summary>
        public static string OPMoreAppsDetail {
            get {
                return ResourceManager.GetString("OPMoreAppsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network errors!Please check and try! 的本地化字符串。
        /// </summary>
        public static string OPNetWorkErrors {
            get {
                return ResourceManager.GetString("OPNetWorkErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option 的本地化字符串。
        /// </summary>
        public static string OPPotion {
            get {
                return ResourceManager.GetString("OPPotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Ads 的本地化字符串。
        /// </summary>
        public static string OPRemoveAds {
            get {
                return ResourceManager.GetString("OPRemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It will take effect after the app restarted. 的本地化字符串。
        /// </summary>
        public static string OPTakeEffectAfterRestart {
            get {
                return ResourceManager.GetString("OPTakeEffectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We are here 的本地化字符串。
        /// </summary>
        public static string OPWeAreHere {
            get {
                return ResourceManager.GetString("OPWeAreHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layers 的本地化字符串。
        /// </summary>
        public static string PPLayers {
            get {
                return ResourceManager.GetString("PPLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Pen 的本地化字符串。
        /// </summary>
        public static string PSPColorPen {
            get {
                return ResourceManager.GetString("PSPColorPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string PSPOpacity {
            get {
                return ResourceManager.GetString("PSPOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opaque Pen 的本地化字符串。
        /// </summary>
        public static string PSPOpaquePen {
            get {
                return ResourceManager.GetString("PSPOpaquePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Pen 的本地化字符串。
        /// </summary>
        public static string PSPOriginalPen {
            get {
                return ResourceManager.GetString("PSPOriginalPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pen Style 的本地化字符串。
        /// </summary>
        public static string PSPPenStyle {
            get {
                return ResourceManager.GetString("PSPPenStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        public static string PSPTransparency {
            get {
                return ResourceManager.GetString("PSPTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent Pen 的本地化字符串。
        /// </summary>
        public static string PSPTransparentPen {
            get {
                return ResourceManager.GetString("PSPTransparentPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The size of the saved: 的本地化字符串。
        /// </summary>
        public static string SavedSize {
            get {
                return ResourceManager.GetString("SavedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Failed! 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        public static string SPBackground {
            get {
                return ResourceManager.GetString("SPBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string SPColor {
            get {
                return ResourceManager.GetString("SPColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        public static string SPFill {
            get {
                return ResourceManager.GetString("SPFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string SPFit {
            get {
                return ResourceManager.GetString("SPFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string SPNone {
            get {
                return ResourceManager.GetString("SPNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        public static string SPOFF {
            get {
                return ResourceManager.GetString("SPOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        public static string SPON {
            get {
                return ResourceManager.GetString("SPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string SPOthers {
            get {
                return ResourceManager.GetString("SPOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo 的本地化字符串。
        /// </summary>
        public static string SPPhoto {
            get {
                return ResourceManager.GetString("SPPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved size 的本地化字符串。
        /// </summary>
        public static string SPSavedSize {
            get {
                return ResourceManager.GetString("SPSavedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show help 的本地化字符串。
        /// </summary>
        public static string SPShowHelp {
            get {
                return ResourceManager.GetString("SPShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string SPSize {
            get {
                return ResourceManager.GetString("SPSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretch 的本地化字符串。
        /// </summary>
        public static string SPStretch {
            get {
                return ResourceManager.GetString("SPStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unifrom 的本地化字符串。
        /// </summary>
        public static string SPUniform {
            get {
                return ResourceManager.GetString("SPUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Color 的本地化字符串。
        /// </summary>
        public static string tBackgroundColor {
            get {
                return ResourceManager.GetString("tBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canva Size: 的本地化字符串。
        /// </summary>
        public static string tBSBoardProportion {
            get {
                return ResourceManager.GetString("tBSBoardProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string tColor {
            get {
                return ResourceManager.GetString("tColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string tDefaultSize {
            get {
                return ResourceManager.GetString("tDefaultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete selected layer? 的本地化字符串。
        /// </summary>
        public static string tDelLayerConfirm {
            get {
                return ResourceManager.GetString("tDelLayerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave 的本地化字符串。
        /// </summary>
        public static string tLeave {
            get {
                return ResourceManager.GetString("tLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to leave? 的本地化字符串。
        /// </summary>
        public static string tLeaveContent {
            get {
                return ResourceManager.GetString("tLeaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Layers? 的本地化字符串。
        /// </summary>
        public static string tMergeLayers {
            get {
                return ResourceManager.GetString("tMergeLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string tOpacity {
            get {
                return ResourceManager.GetString("tOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original 的本地化字符串。
        /// </summary>
        public static string tOriginal {
            get {
                return ResourceManager.GetString("tOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spacing 的本地化字符串。
        /// </summary>
        public static string tSpacing {
            get {
                return ResourceManager.GetString("tSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        public static string tTransparency {
            get {
                return ResourceManager.GetString("tTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A layer had been deleted! 的本地化字符串。
        /// </summary>
        public static string UCALayerHadBeenDeleted {
            get {
                return ResourceManager.GetString("UCALayerHadBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one layer should be kept! 的本地化字符串。
        /// </summary>
        public static string UCOneLayerShouldBeKept {
            get {
                return ResourceManager.GetString("UCOneLayerShouldBeKept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add layer 的本地化字符串。
        /// </summary>
        public static string ULAddLayer {
            get {
                return ResourceManager.GetString("ULAddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add picture 的本地化字符串。
        /// </summary>
        public static string ULAddPicture {
            get {
                return ResourceManager.GetString("ULAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge layers 的本地化字符串。
        /// </summary>
        public static string ULMergeLayers {
            get {
                return ResourceManager.GetString("ULMergeLayers", resourceCulture);
            }
        }
    }
}
